### List companies
GET {{baseUrl}}/companies
Authorization: Bearer {{authToken}}

### Create company
POST {{baseUrl}}/companies
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "code": "COMP-002",
  "name": "Acme Corp2",
  "phone": null,
  "email": null,
  "billing_ref": null,
  "billing_ref_no": null,
  "billing_address": null,
  "active": true
}

### Get company by id
GET {{baseUrl}}/companies/2
Authorization: Bearer {{authToken}}

### Update company
PUT {{baseUrl}}/companies/2
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "name": "Acme Corporation",
  "phone": "+1-555-9876",
  "billing_address": "456 Commerce St, Metropolis",
  "active": true
}

### Delete company
DELETE {{baseUrl}}/companies/2
Authorization: Bearer {{authToken}}