HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Content-Length: 2406
ETag: W/"966-uxl/Ya9AF376Eg3dP7pg3vAqB6U"
Date: Mon, 17 Aug 2026 13:07:47 GMT
Connection: close

{
  "id": 1,
  "company_id": 1,
  "invoice_number": "INV-20260817-0001",
  "invoice_date": "2026-08-17T00:00:00.000Z",
  "service_start_date": "2026-08-17T00:00:00.000Z",
  "service_end_date": "2026-08-17T00:00:00.000Z",
  "po_number": "",
  "location": "",
  "miles": "0",
  "rate_per_mile": "0",
  "mileage_fee": "0",
  "miscellaneous_charges": "0",
  "hourly_fee": "0",
  "subtotal": "100",
  "tax_amount": "0",
  "total_amount": "100",
  "status": "draft",
  "payment_status": "Pending",
  "authorized_by": null,
  "created_by_id": 1,
  "created_at": "2026-08-17T13:01:33.613Z",
  "updated_at": "2026-08-17T13:01:33.613Z",
  "company": {
    "id": 1,
    "code": "NGL",
    "name": "Natty Gas Lab",
    "phone": "(432) 686-2719",
    "email": "",
    "billing_ref": null,
    "billing_ref_no": null,
    "billing_address": "10700 FM 307, Midland, TX 79706",
    "charge_h2_pop_fee": false,
    "h2_pop_fee_rate": "0",
    "pressure_base": null,
    "pressure_base_factor": null
  },
  "invoiceLines": [
    {
      "id": 1,
      "invoice_id": 1,
      "sample_checkin_id": 2,
      "analysis_number": "2026-00002",
      "description": "Water Hardness",
      "service_date": "2026-08-17T00:00:00.000Z",
      "report_number": null,
      "analysis_method": "Water Hardness",
      "quantity": "1",
      "unit_price": "100",
      "amount": "100",
      "created_by_id": 1,
      "created_at": "2026-08-17T13:01:33.613Z",
      "updated_at": "2026-08-17T13:01:33.613Z",
      "sample_checkin": {
        "id": 2,
        "company_id": 1,
        "company_contact_id": 1,
        "analysis_type_id": 1,
        "area_id": 1,
        "customer_cylinder": false,
        "rushed": false,
        "sampled_by_lab": false,
        "cylinder_id": 1,
        "cylinder_number": "30001",
        "analysis_number": "2026-00002",
        "analysis_position": 1,
        "producer": "Apache",
        "well_name": "Mohican CTB",
        "meter_number": "DB 80721",
        "sample_type": "Spot",
        "flow_rate": "2380",
        "pressure": "58",
        "pressure_unit": "PSIG",
        "pressure_measured": "50",
        "temperature": "81",
        "amb_temp": "95 F",
        "sample_time": "14:30",
        "sample_date": "2026-12-10T00:00:00.000Z",
        "sampled_by": "Jared Goldsmith",
        "analyzed_by": null,
        "base_condition": null,
        "physical_constant": null,
        "field_h2s": 2,
        "pressure_base_factor": "0",
        "cost_code": "8007231",
        "checkin_type": "Cylinder",
        "invoice_ref_name": "NA",
        "invoice_ref_value": "",
        "remarks": "Fuel Gas",
        "work_order_number": "WO-2026-0002",
        "status": "Invoiced",
        "standard_rate": "100",
        "applied_rate": "100",
        "sample_fee": "0",
        "h2_pop_fee": "0",
        "spot_composite_fee": "0",
        "import_machine_report_id": 3,
        "company_area": {
          "id": 1,
          "company_id": 1,
          "area": "HQ",
          "region": "NA",
          "description": "Headquarters",
          "gl_code": "GL0001",
          "pay_key": "PAS0001",
          "active": true,
          "created_by_id": 1,
          "created_at": "2026-08-17T11:40:02.452Z",
          "updated_at": "2026-08-17T13:07:43.663Z"
        }
      }
    }
  ]
}