### Get workorder_header by work_order_number
GET {{baseUrl}}/workorder_headers/by-number/WO-584323
Authorization: Bearer {{authToken}}
### List all workorder_headers
GET {{baseUrl}}/workorder_headers
Authorization: Bearer {{authToken}}

### Get workorder_header by id
GET {{baseUrl}}/workorder_headers/1
Authorization: Bearer {{authToken}}

### Create workorder_header
POST {{baseUrl}}/workorder_headers
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "company_id": 1,
  "work_order_date": "2026-01-01T00:00:00.000Z",
  "work_order_number": "WO-492856",
  "cylinders":2,
  "mileage_fee": 10.00,
  "miscellaneous_charges": 5.00,
  "hourly_fee": 20.00,
  "created_by_id": 1,
  "status": "Pending"
}

### Update workorder_header by work_order_number
PUT {{baseUrl}}/workorder_headers/by-number/WO-492856
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "mileage_fee": 124.00,
  "miscellaneous_charges": 644.00,
  "hourly_fee": 242.00,
  "cylinders":2,
  "created_by_id": 1,
  "status": "Submitted"
}

### Just to mark workorer as submitted
PUT {{baseUrl}}/workorder_headers/by-number/WO-492856
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "Submitted"
}


### Delete workorder_header by work_order_number
DELETE {{baseUrl}}/workorder_headers/by-number/WO-0001
Authorization: Bearer {{authToken}}

### Delete workorder_header by id
DELETE {{baseUrl}}/workorder_headers/1
Authorization: Bearer {{authToken}}

### List workorder_headers for invoice
GET {{baseUrl}}/workorder_headers/for_invoice
Authorization: Bearer {{authToken}}
